### ISSUE TITLE
parameter "type" is not validated 

### ISSUE THREAD

**Issue by emmasuzuki** [gargol/swagger-express-validator#10]
I have a swagger spec like below: 

```
{
  ...
  "/somepath": {
    "get": {
      "parameters: [{
        "in": "query",
        "name": "path",
        "required": true,
        "type":"string"
      }] 
     ...
}
```

and when I request with no path in query, validator does not return error. 

Is it not supported yet? 

I am using Swagger version 2.0.

**Comment by gargol** [comment]
Hi @emmasuzuki there's no support for query parameters validation at this point. The only thing that gets validated is request body - https://github.com/gargol/swagger-express-validator/blob/master/index.js#L205 . That would be actually a cool feature to implement in the future

**Comment by emmasuzuki** [comment]
I see, thanks.  I agree it would be nice to have that feature.
