### ISSUE TITLE
parameters order

### ISSUE THREAD

**Issue by giladgreen** [gargol/swagger-express-validator#13]
Hey,
i've notice at the main index.js file, at line 91, that you assume the body propery is the first..
but if my schema define some path and/or query parameters and the body parameter is not the first.. then this will fail..

**Comment by gargol** [comment]
Hey @giladgreen! Could you please provide a sample test case that reproduces this issue? Thanks!

**Comment by Gecko222** [comment]
@gargol 
`json
"parameters" : [ {
          "name" : "X-Message-ID",
          "in" : "header",
          "description" : "Unique message identifier",
          "required" : true,
          "type" : "string",
          "format" : "uuid"
        }, {
          "in" : "body",
          "name" : "body",
          "description" : "Product object that need to be added",
          "required" : true,
          "schema" : {
            "$ref" : "#/definitions/ProductAddRequest"
          }
        } ],`

**Comment by gargol** [comment]
@Gecko222 I think I did it out of convenience, as most of the schemas I was using started with or contained only body description. Would appreciate a PR to change it for something more generic :wink:

**Comment by SebastianStroz** [comment]
Hi,
I see above code is changed to:
`    if (requestSchemas && requestSchemas.length > 0) {
      ([{ schema }] = requestSchemas);
    }
`
I think it should be reopened. I have similar (if not exactly the same) issue with folowing sample:
`        "parameters": [
          {
            "in": "path",
            "name": "someId",
            "type": "string",
            "description": "Some ID for the response",
            "required": true,
            "x-example": "1234567"
          },
          {
            "in": "body",
            "name": "response",
            "description": "Session object.",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UserSession"
            }
          }
        ],
`
See that "someId" parameter has no schema, just type. And line:
`([{ schema }] = requestSchemas);`
returns _undefined_

**Comment by kibertoad** [comment]
@gargol Could you please rropen this? There's a PR with a fix.
