### ISSUE TITLE
Swagger/OpenAPI 3.0 support

### ISSUE THREAD

**Issue by benjamine** [gargol/swagger-express-validator#14]
Hi there, just checking if there's any plan for this lib to add support for it.

I know it's a big change, 
but if it helps, I assume `ajv` already handles the JSON schema updates (anyOf, oneOf) :)

**Comment by gargol** [comment]
Hey @benjamine currently, due to limited free time, can't promise any date for v3.0 support. If anybody comes up with a PR would be happy to review and accept the contribution :)

**Comment by benjamine** [comment]
thanks, it certainly looks like a big upgrade, will stay in 2.0 for now. thanks for an awesome lib!
