### ISSUE TITLE
How do I throw a 400 errors?

### ISSUE THREAD

**Issue by hasanavi** [gargol/swagger-express-validator#19]
in the requestValidationFn: (req, data, errors) => {...}

if I `throw new Error` - it becomes 500. If data validation fails, I would like to throw a 4xx error.
I don't have access to the res object so can't set the status code.
How do I implement error 4xx?

**Comment by gargol** [comment]
Hey :wave: @hasanavi The `requestValidationFn` is not meant to handle responses, it's just a function that you can use to log things the 400 is returned by [default](https://github.com/gargol/swagger-express-validator/blob/48bda9c24f83c260b7f0d1306eb5a5453725ac34/index.js#L228-L232) if you don't provide `requestValidationFn`. Let me know if you have any more questions :)

**Comment by hasanavi** [comment]
Thanks for taking the time to look into this @gargol , Appreciate that.
