### ISSUE TITLE
throw err vs next(err)

### ISSUE THREAD

**Issue by vidishdatta** [gargol/swagger-express-validator#22]
Hi, 

Just trying to understand if there was a particular reason to throw an error instead of using next(err)?

https://github.com/gargol/swagger-express-validator/blob/0e0c0d36cb3aafab021f2885516df5c39b7909ce/index.js#L173

**Comment by kibertoad** [comment]
@gargol Can I fix this?

**Comment by gargol** [comment]
@kibertoad sure :+1: Don't remember the reason why implemented this way :sweat_smile:
