### ISSUE TITLE
Expose Ajv configuration

### ISSUE THREAD

**Issue by kibertoad** [gargol/swagger-express-validator#23]
It is sometimes useful to be able to set options for underlying Ajv instance (e. g. to define handling of type conversion or default). At this point there is no way to pass options to Ajv that swagger-express-validator is instantiating.

**Comment by kibertoad** [comment]
If there is approval for this request, I can provide a PR for it.

**Comment by gargol** [comment]
Yes @kibertoad this seems like a sensible thing to add to configuration :+1:
