### ISSUE TITLE
Does this support the `defining-custom-keywords` functionality given by AJV 

### ISSUE THREAD

**Issue by ksuperman** [gargol/swagger-express-validator#38]
I was hoping to see if this Library support creating validation scenarios that is already supported by ajv.

**Usecase**
Need to handle customer swagger schema element validations

https://github.com/epoberezkin/ajv/blob/master/README.md#defining-custom-keywords

**Comment by kibertoad** [comment]
I don't think so. PRs welcome! And I think https://www.npmjs.com/package/express-ajv-swagger-validation already has support for it, so you may give it a try.

**Comment by ksuperman** [comment]
thanks :) i used https://www.npmjs.com/package/express-ajv-swagger-validation it works and matches  my use case

**Comment by kibertoad** [comment]
@ksuperman Happy to hear that!
